# Generated by Django 5.2.13 on 2026-05-18 06:29

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=users.models.generate_employee_id, max_length=6, unique=True),
        ),
    ]
