# Generated by Django 5.2.13 on 2026-05-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_description_ticket_query_remove_ticket_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_level',
            field=models.CharField(choices=[('L3', 'L3'), ('L2', 'L2'), ('L1', 'L1')], default='L3', max_length=2),
        ),
    ]
