# Generated by Django 5.2.13 on 2026-06-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_ticket_level_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='level',
            new_name='ticket_level',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
