# Generated by Django 5.2.13 on 2026-06-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_level_ticket_ticket_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
