# Generated by Django 5.2.13 on 2026-07-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_escalation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
