# Generated by Django 5.2.13 on 2026-07-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='query',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_level',
            new_name='current_level',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='classification',
            new_name='predicted_queue',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='suggested_resolution',
            new_name='resolution',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='escalation_reason',
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
