# Generated by Django 5.2.13 on 2026-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_rename_query_ticket_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='classifier_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
